export const FB_AUTH_SUCCESS = "FB_AUTH_SUCCESS";
export const EMAIL_AUTH_SUCCESS = "EMAIL_AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const EMAIL_CHANGE = "EMAIl_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
